version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: 'postgres-upload-video'
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/db/upload-video:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres